### ISSUE TITLE
Unable to stay connected after closing extension window

### ISSUE THREAD

**Issue by Therkelsen** [ZEBAS204/adobe_wakatime#2] opened 2023-11-06 03:24 UTC
Windows 10 22H2
Premiere Pro 23.1.0

I've noticed two things:
1. The plugin doesn't save the API key, so I have to re-enter it upon restart of Premiere.
2. When I close the extension window, it disconnects from the wakatime api.

Is this intended? It would be nice if I could just enter the API key once, and then it auto logs in upon startup of premiere, and to stay connected when the extension window isn't open.

**Comment by ZEBAS204** [comment] 2023-11-07 21:41
Sorry, Github decided to notify me about your issue 2 days later...

1. **API key not being saved:** This is not intended, and the extension *should* save and restore your settings properly.
However, I've noticed that sometimes the extension's full storage is cleared randomly, and I have no idea why this happens or how to prevent it.
    It's worth noting that this problem is similar to what was reported in a 2016 issue:
   Adobe-CEP/CEP-Resources#52

---

2. **Disconnecting when closing the extension panel:** All Adobe applications that support extensions automatically unload the extension when you close its window. This behavior is by design. You either have to keep it collapsed or open somewhere.

     As a workaround for Premiere Pro/After Effects, you can dock the panel to the Composition Preview panel, since it is large enough, and adding another panel won't be a bother there.
     Alternatively; you can undock the panel, collapse the window as much as you can, and move it to the top so it doesn't bother.

---

I will update the Readme to give more information about these unavoidable minor issues.
In the next release, all saved settings will be restored at startup, rather than waiting until the first API call after 2min.
So it will be easy to tell whether the settings were lost or not.

Let me know if you have any more questions or concerns ^^

**Comment by ZEBAS204** [comment] 2023-11-10 21:04
It should be more straightforward to know if the settings have been deleted with the latest version

**Closed as completed by ZEBAS204** 2023-11-10 21:04 UTC
